# Generated by Django 4.2.3 on 2023-10-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_produt_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ription',
        ),
    ]
